db_version = "5.7"
ssl_enforcement = "Enabled"
backup_retention_days = 7
geo_redundant_backup = "Disabled"
charset = "utf8"
collation = "utf8_unicode_ci"
auto_grow = "Disabled"
tags = {}
mysql_options = []
allowed_cidrs = [ "192.168.1.0/24" ]
